# Generated by Django 4.2.6 on 2023-11-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.IntegerField(verbose_name='уникальный номер')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery_address', models.TextField(blank=True, verbose_name='адрес доставки')),
                ('client_phone_number', models.TextField(blank=True, verbose_name='телефон клиента')),
                ('Clients_full_name', models.TextField(blank=True, verbose_name='ФИО клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Цена')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обнавления')),
                ('exist', models.BooleanField(default=True, verbose_name='существует')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.category')),
                ('tag', models.ManyToManyField(to='ProjectSite.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products_per_position', models.IntegerField(verbose_name='Кол-во товара')),
                ('discount_per_item', models.IntegerField(verbose_name='Скидка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProjectSite.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProjectSite.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='ProjectSite.Order_item', to='ProjectSite.product'),
        ),
    ]
